---
title: "viz_part1"
author: "Shivangi Mewada"
output: github_document
---

```{r}
library(tidyverse)
library(ggridges)
```

```{r weather}
weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728", "USC00519397", "USS0023B17S"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2017-01-01",
    date_max = "2017-12-31") %>%
  mutate(
    name = recode(
      id, 
      USW00094728 = "CentralPark_NY", 
      USC00519397 = "Waikiki_HA",
      USS0023B17S = "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10) %>%
  select(name, id, everything())

```

lets make a scatterplot

```{r}
ggplot (weather_df, aes(x = tmin, y = tmax)) + geom_point()
```


```{r}
weather_df %>%
drop_na() %>%
  filter(name == "CentralPark_NY") %>%
ggplot(aes(x = tmin, y = tmax)) + geom_point()
```

```{r}
WEATHER_SCATTERPLOT = 
weather_df %>%
drop_na() %>%
  
ggplot (aes(x = tmin, y = tmax))

WEATHER_SCATTERPLOT + geom_point()

```

## fancy

```{r}
weather_df %>%
  ggplot(aes(x = tmin, y = tmax)) + geom_point(aes(color = name)) + geom_smooth()
```

## changes in smooth

```{r}
weather_df %>%
  ggplot(aes(x = tmin, y = tmax, color = name)) + geom_point(alpha = 0.3) + geom_smooth(se = FALSE)

```

```{r do not do this in practical}
weather_df %>%
  ggplot(aes(x = tmin, y = tmax, color = name)) + geom_smooth(se = FALSE)

```

## make separate panels

```{r}
weather_df %>%
  ggplot(aes(x = tmin, y = tmax, color = name)) + geom_point(alpha = 0.3) + geom_smooth(se = FALSE) + facet_grid(. ~ name)
```

## tmin and tmax are boring

```{r}
weather_df %>%
  ggplot(aes(x = date, y = tmax, color = name)) + geom_point(alpha = 0.3) + geom_smooth(se = FALSE)+ facet_grid(. ~ name)
```

```{r}
weather_df %>%
  ggplot(aes(x = date, y = tmax, color = name)) + geom_point(aes(size = prcp),alpha = 0.3) + geom_smooth(se = FALSE)+ facet_grid(. ~ name)
```

## quick stuff

```{r}
weather_df %>%
  ggplot(aes(x = tmin, y = tmax)) + geom_hex()
```

## univariate

```{r}
weather_df %>%
  ggplot(aes(x = tmax, fill = name)) + geom_histogram() + facet_grid(. ~ name)
```

## more options

```{r}
weather_df %>%
  ggplot(aes(x = tmax, fill = name)) + geom_density(alpha = .3)
```

## boxplots

```{r}
weather_df %>%
  ggplot(aes(x = name, y = tmax, fill = name)) + geom_boxplot()
```

```{r}
weather_df %>%
  ggplot(aes(x = name, y = tmax, fill = name)) + geom_violin()
```

or 

```{r}
weather_df %>%
  ggplot(aes(x = tmax, y = name)) + geom_density_ridges()
```

